### ISSUE TITLE
open external links in new tab

### ISSUE THREAD

**Issue by Strryke** [natalieagus/50002#14]
add target="_blank" for external links so they open in a new tab.

i think this would be a nice QoL change. i can look into implementing this if you approve

**Comment by natalieagus** [comment]
Made a commit f33e57d8088de753be84ecb154a563d6ed935caf
I think that should do it, help me check the site when you have time. 

Just did a basic regex search:
(\]\(https://[^\[\n]+\))

And replace with $1{:target="_blank"} 

Should've used a better web framework, well, next year or two :)

**Update**: Nevermind, some paragraphs are deleted because of it, i shall revert. Yup please look to it when you have the time, thanks!

**Comment by Strryke** [comment]
I found a gem that achieves this: https://rubygems.org/gems/jekyll-target-blank. 

if you're not keen on adding extra dependencies, I also found a JS snippet that should work: https://raw.githubusercontent.com/jhvanderschee/jekyllcodex/gh-pages/_includes/new-window-fix.html

which solution would you prefer?

**Comment by natalieagus** [comment]
Thank you for the options. Seems like the snippet works :) 59d3e0e2665d6c38a7f3b83ebcf12d33aa4cc529
Adding gems should be fine too, but eventually I might change web frameworks so I try to have all features I want to be as portable as possible. 

Please help me check, if it works, I will close this issue. Appreciate your help!

**Comment by Strryke** [comment]
lgtm! thanks prof. look forward to spending a lot more time on this site :"
